version: '3.8'

services:
  api:
    build: ./services/api
    ports:
      - "8000:8000"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    volumes:
      - ./services/api:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  device-mgmt:
    build: ./services/device-mgmt
    ports:
      - "8001:8001"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    volumes:
      - ./services/device-mgmt:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload

  analytics:
    build: ./services/analytics
    ports:
      - "8002:8002"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    volumes:
      - ./services/analytics:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8002 --reload

networks:
  default:
    driver: bridge