name: Frontend CI

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    
    - name: Install dependencies
      run: |
        cd frontend
        npm ci
        # Explicitly install react-router-dom to ensure it's available for tests
        npm install --save react-router-dom
        # Install ESLint for linting
        npm install --save-dev eslint eslint-plugin-react
    
    - name: Add lint script to package.json
      run: |
        cd frontend
        if ! grep -q "\"lint\":" package.json; then
          sed -i 's/"scripts": {/"scripts": {\n    "lint": "eslint src --ext .js,.jsx,.ts,.tsx",/g' package.json
        fi
    
    - name: Create ESLint config if needed
      run: |
        cd frontend
        if [ ! -f ".eslintrc.json" ]; then
          echo '{
            "extends": ["react-app"],
            "rules": {
              "no-unused-vars": "warn"
            }
          }' > .eslintrc.json
        fi
    
    - name: Run linting
      run: |
        cd frontend
        npm run lint
    
    - name: Run tests
      run: |
        cd frontend
        CI=true npm test
    
    - name: Build application
      run: |
        cd frontend
        npm run build
    
    - name: Upload coverage report
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./frontend/coverage/lcov.info
        flags: frontend
        fail_ci_if_error: false